### ISSUE TITLE
[Feature Request] Comments disabled by option

### ISSUE THREAD

**Issue by Novack** [YclepticStudios/vscode-unity-snippets#1]
Hello! Very nice extension! Your work is very appreciated.

I'd like to ask for a feature to be added: allow to deactivate the comments on the inserted snippets, by an option in the settings. Nothing too elaborated, but a bool to control to either insert comments or not would be nice, I sistematically need to delete the comments after inserting the methods, which sort of defeats the purpose of having them in the first place :)

Thanks!

**Comment by YclepticStudios** [comment]
Hey, glad you like it!

Unfortunately, I am unaware of any method to create a settings option for snippets. The plugin is basically a huge JSON object which VS Code interprets, providing little flexibility for extra features.

If there was a reasonably easy way to add this, I would; but the only way I can think of is to rewrite this as a true plugin.

**Comment by Novack** [comment]
Ah, at least I know I can modify the snippets myself. Thanks again!

**Comment by YclepticStudios** [comment]
No problem!
